TRUNCATE TABLE user_roles RESTART IDENTITY;
TRUNCATE TABLE users RESTART IDENTITY;
TRUNCATE TABLE roles RESTART IDENTITY;
TRUNCATE TABLE user_sessions RESTART IDENTITY;

SELECT * FROM users;
SELECT * FROM user_sessions;