### Main API Test Entry Point
# See individual controller files for specific tests:
# - auth-controller.http
# - user-controller.http
# - simulation-controller.http
# - test-controller.http

### Check Swagger UI
GET {{host}}/swagger-ui.html

### Check API Docs
GET {{host}}/v3/api-docs
