### Simulate Stream Start
POST {{host}}/api/dev/simulate/stream/start
Content-Type: application/json

{
  "streamKey": "{{stream_key}}"
}

### Simulate Stream End
POST {{host}}/api/dev/simulate/stream/end
Content-Type: application/json

{
  "streamKey": "{{stream_key}}"
}

### Simulate Payment Deposit
POST {{host}}/api/dev/simulate/payment/deposit
Content-Type: application/json

{
  "userId": 1,
  "amount": 1000.00
}
